apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rainmaker

commonLabels:
  app.kubernetes.io/part-of: rainmaker

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.placeholder.yaml
  - postgres/
  - garage/
  - vernemq/
  - api/
  - vmq-authz/
  - mqtt-ingestor/
  - worker/
  - migrations-job.yaml
  - ingress.yaml
  - networkpolicies.yaml

images:
  - name: rainmaker-server
    newTag: 0.1.0
