apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rainmaker-staging

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: rainmaker-config
    patch: |-
      - op: replace
        path: /data/RM_ENV
        value: staging
