apiVersion: v1
kind: Service
metadata:
  name: vernemq
  labels:
    app.kubernetes.io/name: vernemq
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: vernemq
  ports:
    - name: mqtt-tls
      port: 8883
      targetPort: mqtt-tls
    - name: mqtt-wss
      port: 8084
      targetPort: mqtt-wss

---
apiVersion: v1
kind: Service
metadata:
  name: vernemq-internal
  labels:
    app.kubernetes.io/name: vernemq
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: vernemq
  ports:
    - name: mqtt-tls
      port: 8883
      targetPort: mqtt-tls
    - name: http
      port: 8888
      targetPort: http
