"""SQLAlchemy ORM models.

Importing this package registers all tables with the shared metadata,
which Alembic relies on for autogenerated migrations.
"""

from app.models.device_provisioning import ClaimChallenge, DeviceProvisioning  # noqa: F401
from app.models.node import (  # noqa: F401
    Node,
    NodeAttribute,
    NodeCertificate,
    NodeConfig,
    NodeParamsShadow,
)
from app.models.ota import OtaImage, OtaJob, OtaJobNode  # noqa: F401
from app.models.sharing import (  # noqa: F401
    NodeGroup,
    NodeGroupNode,
    NodeSharing,
    NodeSharingRequest,
)
from app.models.user import RefreshToken, User  # noqa: F401
from app.models.user_node import MappingChallenge, UserNodeMapping  # noqa: F401
